tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "anyenv"
brew "brainfuck"
brew "cask"
brew "colordiff"
brew "docker"
brew "fish"
brew "ghq"
brew "gibo"
brew "git"
brew "grep"
brew "jq"
brew "less"
brew "lv"
brew "mas"
brew "mkcert"
brew "nkf"
brew "nss"
brew "nyancat"
brew "pandoc"
brew "peco"
brew "sl"
brew "source-highlight"
brew "speedtest-cli"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "unar"
brew "wget"
cask "1password"
cask "atom"
cask "basictex"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "flotato"
cask "fork"
cask "google-chrome-canary"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "gyazo"
cask "hyper"
cask "linear"
cask "ngrok"
cask "pock"
cask "runjs"
cask "sourcetree"
cask "visual-studio-code"
cask "wkhtmltopdf"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
